add_requires("raylib", "nlohmann_json", "nativefiledialog-extended", "raygui", "alpaca", "reproc")
add_rules("mode.debug")
set_defaultmode("debug")

target("rpgpp")
    set_kind("static")
	set_languages("cxx17")
    add_includedirs("include/")
    add_files("src/*.cpp")
    add_packages("raylib", "nlohmann_json", "alpaca")
    add_links("lua")
    set_targetdir("./")
    if is_plat("linux") then
        add_cxxflags("-fPIC")
    end

target("rpgpplua")
    set_kind("shared")
	set_languages("cxx17")
    add_includedirs("include/")
    add_files("src/rpgpplua/*.cpp")
    add_packages("nlohmann_json", "raylib", "alpaca", {public = true})
    add_links("lua")
	add_deps("rpgpp")
    set_targetdir("./")

target("editor")
    set_kind("binary")
	set_languages("cxx17")
    add_includedirs("include/", "include/editor/")
    add_files("src/editor/*.cpp")
    add_packages("raylib", "nlohmann_json", "nativefiledialog-extended", "raygui", "reproc")
	add_links("lua")
    add_deps("rpgpp")
    set_targetdir("./")

target("game")
    set_kind("binary")
	set_languages("cxx17")
    add_includedirs("include/")
    add_files("src/game/*.cpp")
    add_packages("raylib", "nlohmann_json")
	add_links("lua")
    add_deps("rpgpp")
    set_targetdir("./")

