add_requires("raylib", "nlohmann_json", "nativefiledialog-extended", "raygui")
set_defaultmode("debug")

target("rpgpp")
    set_kind("static")
    add_includedirs("include/")
    add_files("src/*.cpp")
    add_packages("raylib", "nlohmann_json")
    set_targetdir("./")

target("editor")
    set_kind("binary")
    add_includedirs("include/", "include/editor/")
    add_files("src/editor/*.cpp")
    add_packages("raylib", "nlohmann_json", "nativefiledialog-extended", "raygui")
    add_deps("rpgpp")
    set_targetdir("./")

target("game")
    set_kind("binary")
    add_includedirs("include/")
    add_files("src/game/*.cpp")
    add_packages("raylib", "nlohmann_json")
    add_deps("rpgpp")
    set_targetdir("./")

