add_requires("raylib", "nlohmann_json", "nativefiledialog-extended", "alpaca", "reproc")
add_rules("mode.debug")
set_defaultmode("debug")

task("resources")
    on_run(function()
       os.cp("$(curdir)/resources", "$(builddir)/$(plat)/$(arch)/$(mode)/resources")
    end)

target("rpgpp")
    set_kind("static")
	set_languages("cxx17")
    add_includedirs("include/")
    add_files("src/*.cpp")
    add_packages("raylib", "nlohmann_json", "alpaca")
    if is_plat("linux") then
        add_cxxflags("-fPIC")
    end

target("rpgpplua")
    set_kind("shared")
	set_languages("cxx17")
    add_includedirs("include/", "libs/luajit/src/")
    add_files("src/rpgpplua/*.cpp")
    add_packages("nlohmann_json", "raylib", "alpaca", {public = true})
    add_linkdirs("libs/")
    add_links("luajit")
	add_deps("rpgpp")

target("editor")
    set_kind("binary")
	set_languages("cxx17")
    add_includedirs("include/", "include/editor/", "include/imgui/")
    add_files("src/editor/*.cpp")
    add_packages("raylib", "nlohmann_json", "nativefiledialog-extended", "reproc")
	add_links("luajit", "rlImGui")
    add_linkdirs("libs/")
    add_deps("rpgpp")
    after_build(function ()
        import("core.project.task")
        task.run("resources")
    end)

target("game")
    set_kind("binary")
	set_languages("cxx17")
    add_includedirs("include/")
    add_files("src/game/*.cpp")
    add_packages("raylib", "nlohmann_json")
    add_linkdirs("libs/")
	add_links("luajit")
    add_deps("rpgpp")

