name: "Build documentations"

on:
    push:
        branches: ["main", "docs"]
    pull_request:
        branches: ["main", "docs"]
    workflow_dispatch:

jobs:
    build-docs:
        name: "build docs"
        runs-on: "ubuntu-latest"
        env:
            PLATFORM: linux
            ARCH: x86_64

        steps:
            - name: Checkout repository
              uses: actions/checkout@v6
              with:
                  fetch-depth: 0
                  submodules: recursive

            - name: Install Python
              uses: actions/setup-python@v6
              with:
                  python-version: "3.13"

            - name: Install packages
              shell: bash
              run: |
                  sudo apt install doxygen
            - name: Setup Python environment
              shell: bash
              run: |
                  pip install -r requirements.txt

            - name: Build
              shell: bash
              run: |
                  mkdir -p build/
                  doxygen doxygen.conf
                  breathe-apidoc -o docs/Dev -m -f build/doxygen/xml
                  make html

            - name: Generate token
              id: generate_token
              uses: actions/create-github-app-token@v3
              with:
                  app-id: ${{ secrets.DOC_PUSHER_APP_ID }}
                  private-key: ${{ secrets.DOC_PUSHER_APP_SECRET }}
                  owner: ${{ github.repository_owner }}

            - name: Push to Destination
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"

                  # Use the dynamic token generated by the App
                  git clone https://x-access-token:${{ steps.generate_token.outputs.token }}@github.com/${{ github.repository_owner }}/docs.git dest

                  cp -rf build/html/* dest/
                  cd dest
                  git add .
                  git commit -m "Org sync from ${{ github.repository }}"
                  git push origin main
